### ISSUE TITLE
C++ example request

### ISSUE THREAD

**Issue by dev-plvlml** [chili-epfl/qtphysics-unofficial#4]
Hello @lorenzolightsgdwarf,
Could you add a C++ (not QML) minimal example of using the library and the bullet plugin? E.g., adding physics aspect, adding world and body components, and working with bullet factory the right way. It would be very helpful since Qt docs lack any examples of subclassing aspects and components at the moment, and you seem to have moved pretty far.
With best regards.

**Comment by lorenzolightsgdwarf** [comment]
Hi @dev-plvlml,
I'm working on the example. Anyway, I don't think the example will clarify the way the QT3D backend works and how to integrate a new aspect. For that you should have a look at the code and do a bit of reverse engineering (navigate the original code with https://code.woboq.org/qt5/qt3d/src/). You can ask me in private if something is not clear. 
Kind Regards

**Comment by dev-plvlml** [comment]
Got it, thank you!
